### ISSUE TITLE
Instructions Wiki

### ISSUE THREAD

**Issue by biship** [jeanlouisferey/aws-securitygroup-grapher#1]
Any chance for a simple "how to run" this wiki page?
I appreciate your work here.

**Comment by SinghDivneet** [comment]
Hey ,  @jeanlouisferey  would like to contribute to the wiki here to make it little simpler . Let me know where do i start ?

**Comment by jeanlouisferey** [comment]
Hey @biship and @SinghDivneet ,

I added an "how to run" in https://github.com/jeanlouisferey/aws-securitygroup-grapher/blob/master/README.md#example-playbook.

Is it enough for you ?

(let me be clear: I don't want to explain how to install Ansible and Boto)

**Comment by SinghDivneet** [comment]
works , thanks :+1:
